spring:
    datasource:
        url:
        driver-class-name:
        username:
        password:


    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
        ddl-auto: none
    properties:
        hibernate:
            format_sql: true
    defer-datasource-initialization: false

    logging:
        level:
            sql: debug
            org.hibernate.type: INFO